name: Test
on:
  push:

jobs:
  test:
    strategy:
      matrix:
        node-version: [20, 22]
    uses: driimus/shared-workflows/.github/workflows/test.yml@main
    with:
      node-version: ${{ matrix.node-version }}

  lint:
    uses: driimus/shared-workflows/.github/workflows/lint.yml@main
